// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaYJUKq4GV-KNQ-9KAMIvKJ0hXB1FgctA',
    appId: '1:574469793601:web:c5b63cd94bb47ac230a3c0',
    messagingSenderId: '574469793601',
    projectId: 'habit-tracker586',
    authDomain: 'habit-tracker586.firebaseapp.com',
    storageBucket: 'habit-tracker586.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAic_WvUYzXhfuKQL6rvbvKLQ8Em3Xbe4w',
    appId: '1:574469793601:android:8273c5f70564d81030a3c0',
    messagingSenderId: '574469793601',
    projectId: 'habit-tracker586',
    storageBucket: 'habit-tracker586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTkGtcXWt3yXar1Gty0BFZVT4YaaGhHI',
    appId: '1:574469793601:ios:d4fdfa4b33163d4930a3c0',
    messagingSenderId: '574469793601',
    projectId: 'habit-tracker586',
    storageBucket: 'habit-tracker586.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTkGtcXWt3yXar1Gty0BFZVT4YaaGhHI',
    appId: '1:574469793601:ios:d4fdfa4b33163d4930a3c0',
    messagingSenderId: '574469793601',
    projectId: 'habit-tracker586',
    storageBucket: 'habit-tracker586.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaYJUKq4GV-KNQ-9KAMIvKJ0hXB1FgctA',
    appId: '1:574469793601:web:603794796b59293430a3c0',
    messagingSenderId: '574469793601',
    projectId: 'habit-tracker586',
    authDomain: 'habit-tracker586.firebaseapp.com',
    storageBucket: 'habit-tracker586.firebasestorage.app',
  );
}
